### ISSUE TITLE
We should say something about the January 2018 conference

### ISSUE THREAD

**Issue by kwalrath** [dart-lang/site-events#5]
A placeholder, at least... It looks bad to go to events.dartlang.org and have the latest date be 2016.

http://news.dartlang.org/2017/07/announcing-dartconf.html

**Comment by wmleler** [comment]
I think Linda Rasmussen is working on this.

**Comment by filiph** [comment]
How about I 302 redirect events.dartlang.org to the blogpost announcement? That's easy to do.

**Comment by kwalrath** [comment]
SGTM
